[package]
name = "integration-tests"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
lazy_static = "1"
reqwest = { version = "0.9", default-features = false }

[features]
default = []
test_wasm32_unknown_unknown = []
