[package]
name = "integration-tests"
version = "0.1.0"
authors = ["Jan Bujak <j@exia.io>"]

[dependencies]
lazy_static = "1"
reqwest = { version = "0.9", default-features = false }

[build-dependencies]
rustc_version = "0.2"

[features]
default = []
test_rust_nightly = []
